export const projectsData: Project[] = [
    {
        id: 1,
        title: 'Линия брикетирования Pini & kay',
        location: 'Никольск (Вологодская обл.)',
        year: '2025',
        month: 'Август',
        category: 'Брикетирование',
        description: 'Сырье подается в накопительный бункер, далее проходя через аэродинамическую сушильную линию поступает на брикетирование. Готовый продукт — брикет Pini & kay.',
        image: '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2025-08-briquetting-vologda-video.mp4',
        gallery: [
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-main.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-1.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-2.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-3.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-4.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-5.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-6.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-7.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-8.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-9.webp',
        ],
        slug: '2025-08-briquetting-vologda',
        capacity: '500 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 500 кг/час',
            'Аэродинамическая сушильная линия',
        ]
    },
    {
        id: 2,
        title: 'Линия брикетирования (пресс Nielsen)',
        location: 'Борисово-Судское (Вологодская обл.)',
        year: '2025',
        month: 'Июль',
        category: 'Брикетирование',
        description: 'В данной линии установлены три приёмных живых пола: первый — для крупного сырья, второй — для мелкого сырья, третий — для топлива теплогенератора. Мелкое сырье сразу поступает в сушку, крупное проходит через дробилку. После сушки сырьё поступает в ударно-набивной пресс. Дополнительно установлен стокерный склад для накопления высушенного сырья перед прессованием.',
        image: '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-main.webp',
        gallery: [
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-main.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-1.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-2.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-3.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-4.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-5.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-6.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-7.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-8.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-9.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-10.webp',
        ],
        slug: '2025-07-drying-vologda',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Три приёмных живых пола',
            'Стокерный склад для накопления сырья',
            'Ударно-набивной пресс Nielsen',
        ]
    },
    {
        id: 3,
        title: 'Линия брикетирования',
        location: 'Пермский край',
        year: '2025',
        month: 'Июнь',
        category: 'Брикетирование',
        description: 'Сырьё в данной линии — опил и щепа. Всё сырьё просеивается и делится на фракции: мелкое сырьё сразу уходит в сушку, крупное проходит через дробилку и поступает в сушку. После сушки сырьё брикетируется.',
        image: '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2025-06-briquetting-perm-video.mp4',
        gallery: [
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-main.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-1.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-2.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-3.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-4.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-5.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-6.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-7.webp',
        ],
        slug: '2025-06-briquetting-perm',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Просев и разделение сырья на фракции',
        ]
    },
    {
        id: 4,
        title: 'Линия брикетирования (пресс Nielsen)',
        location: 'Усть-Кулом (Республика Коми)',
        year: '2024',
        month: 'Апрель',
        category: 'Брикетирование',
        description: 'В данной линии установлены два приёмных живых пола: в один насыпается крупное сырьё, в другой — мелкое. Мелкое сырьё сразу поступает в сушку, крупное проходит через дробилку. После сушки сырьё поступает в ударно-набивной пресс.',
        image: '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-main.webp',
        gallery: [
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-main.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-1.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-2.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-3.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-4.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-5.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-6.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-7.webp',
        ],
        slug: '2024-04-drying-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Два приёмных живых пола',
            'Ударно-набивной пресс Nielsen',
        ]
    },
    {
        id: 5,
        title: 'Линия гранулирования',
        location: 'Никольск (Вологодская обл.)',
        year: '2023',
        month: 'Декабрь',
        category: 'Гранулирование',
        description: 'Сырьё в данной линии — опил и щепа естественной влажности. Всё сырьё просеивается и делится на фракции: мелкое сырьё сразу уходит в сушку, крупное проходит через дробилку.',
        image: '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-main.webp',
        gallery: [
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-main.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-1.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-2.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-3.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-4.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-5.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-6.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-7.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-8.webp',
        ],
        slug: '2023-12-granulation-vologda',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Просев и разделение сырья на фракции',
        ]
    },
    {
        id: 6,
        title: 'Линия брикетирования Pini & kay',
        location: 'Мирный (Кировская обл.)',
        year: '2023',
        month: 'Июнь',
        category: 'Брикетирование',
        description: 'Горбыль измельчается в щепу в рубительной машине. Получаемая щепа поступает в накопитель «Живое дно», откуда подаётся в теплогенератор (в качестве топлива) и в дробильную установку для предварительного измельчения. Из дробилки сырьё поступает в сушильный барабан, затем додрабливается в вакуумной дробилке и через шнековый дозатор — в брикетирующий пресс.',
        image: '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-main.webp',
        gallery: [
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-main.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-1.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-2.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-3.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-4.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-5.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-6.webp',
        ],
        slug: '2023-06-briquetting-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Горбыль, щепа хвойных пород',
            'Производительность: 1000 кг/час',
            'Рубительная машина для горбыля',
            'Вакуумная молотковая дробилка',
        ]
    },
    {
        id: 7,
        title: 'Линия брикетирования Pini & kay',
        location: 'Кез (Республика Удмуртия)',
        year: '2022',
        month: 'Декабрь',
        category: 'Брикетирование',
        description: 'Линия брикетирования (pini & kay) из сырых древесных опилок мелкой фракции. Сырье просеивается и сразу отправляется в сушку и далее на прессование.',
        image: '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-main.webp',
        gallery: [
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-main.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-1.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-2.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-3.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-4.webp',
        ],
        slug: '2022-12-briquetting-udmurtia',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 8,
        title: 'Линия пеллетирования, брикетирования и сушки',
        location: 'Ханты-Мансийский АО — Югра',
        year: '2022',
        month: 'Декабрь',
        category: 'Комбинированные линии',
        description: 'Горбыль измельчается в щепу в рубительной машине. Далее щепа загружается в накопитель "Живое дно". Из "Живого дна" щепа автоматически поступает в дробилку для предварительного измельчения. После сушки сырьё поступает в пресс-гранулятор или пресс-брикетер. Теплогенератор сушки работает на газу.',
        image: '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2022-12-combined-khmao-video.mp4',
        gallery: [
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-main.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-1.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-2.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-3.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-4.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-5.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-6.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-7.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-8.webp',
        ],
        slug: '2022-12-combined-khmao',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Горбыль, щепа',
            'Производительность: 1000 кг/час',
            'Теплогенератор: газовый',
        ]
    },
    {
        id: 9,
        title: 'Линия сушки',
        location: 'Республика Коми',
        year: '2022',
        month: 'Август',
        category: 'Сушка',
        description: 'В данной линии осуществляется раздельная подача сырья на сушку и топлива для теплогенератора. Сырье в сушку поступает из живого дна №1. Топливо в теплогенератор поступает из живого дна №2. Таким образом сырье не смешивается и в качестве топлива можно использовать кору, некачественный опил и т.д.',
        image: '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2022-08-drying-komi-video.mp4',
        gallery: [
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-main.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-1.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-2.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-3.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-4.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-5.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-6.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-7.webp',
        ],
        slug: '2022-08-drying-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 1000 кг/час',
            'Раздельная подача сырья и топлива',
        ]
    },
    {
        id: 10,
        title: 'Линия брикетирования Pini & kay',
        location: 'Суслонгер (Республика Марий Эл)',
        year: '2020',
        month: 'Сентябрь',
        category: 'Брикетирование',
        description: 'Щепа с помощью гидравлического живого дна, проходя через сепаратор для отделения крупнокусковых включений, ссыпается на L-образный скребковый транспортер, из которого основная масса поступает в дробилку, а часть щепы подается в бункер теплогенератора в качестве топлива. Из дробилки измельченное сырье поступает в сушку, далее — на прессование.',
        image: '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2020-09-briquetting-mari-el-video.mp4',
        gallery: [
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-main.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-1.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-2.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-3.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-4.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-5.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-6.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-7.webp',
        ],
        slug: '2020-09-briquetting-mari-el',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Щепа лиственных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Гидравлическое живое дно',
        ]
    },
    {
        id: 11,
        title: 'Линия гранулирования',
        location: 'Сыктывкар (Республика Коми)',
        year: '2020',
        month: 'Март',
        category: 'Гранулирование',
        description: 'Сырье из живого дна, проходя через сепаратор для отделения крупнокусковых включений, разделяется просеивающим устройством на мелкую (опил → в сушку) и крупную (щепа → в теплогенератор) фракции. При переполнении бункера теплогенератора крупная фракция перенаправляется в дробилку и далее в сушку.',
        image: '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2020-03-granulation-komi-video.mp4',
        gallery: [
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-main.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-1.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-2.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-3.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-4.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-5.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-6.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-7.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-8.webp',
        ],
        slug: '2020-03-granulation-komi',
        capacity: '2000 кг/час',
        specs: [
            'Сырье: Опил, щепа хвойных пород, естественная влажность',
            'Производительность: 2000 кг/час',
            'Раздельная подготовка фракций',
        ]
    },
    {
        id: 12,
        title: 'Линия сушки',
        location: 'Котлас (Архангельская обл.)',
        year: '2019',
        month: 'Сентябрь',
        category: 'Сушка',
        description: 'В данной линии осуществляется раздельная подача сырья на сушку и топлива для теплогенератора. Сырье в сушку поступает из живого дна №1 с помощью скребкового транспортера. Топливо в теплогенератор поступает из живого дна №2. Таким образом сырье не смешивается и в качестве топлива можно использовать кору, гнилой опил и т.д.',
        image: '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-main.webp',
        gallery: [
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-main.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-1.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-2.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-3.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-4.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-5.webp',
        ],
        slug: '2019-09-drying-kotlas',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Раздельная подача сырья и топлива',
        ]
    },
    {
        id: 13,
        title: 'Линия брикетирования RUF',
        location: 'Кировская область',
        year: '2019',
        month: 'Июль',
        category: 'Брикетирование',
        description: 'Сырьем для изготовления брикетов является опил, щепа и обрезь торцовки, которые ранее вывозились на спецплощадку. КировБелМаш спроектировал линию со шредером для измельчения обрезков в щепу, молотковой дробилкой и сушильным барабаном. После сушки из сырья прессуется брикет RUF.',
        image: '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2019-07-briquetting-kirov-video.mp4',
        gallery: [
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-main.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-1.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-2.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-3.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-4.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-5.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-6.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-7.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-8.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-9.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-10.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-11.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-12.webp',
        ],
        slug: '2019-07-briquetting-kirov',
        capacity: '600 кг/час',
        specs: [
            'Сырье: Опил, щепа, обрезь торцовки хвойных пород, естественная влажность',
            'Производительность: 600 кг/час',
            'Шредер для измельчения обрезков',
        ]
    },
    {
        id: 14,
        title: 'Линия гранулирования',
        location: 'Кировская область',
        year: '2018',
        month: 'Июнь',
        category: 'Гранулирование',
        description: 'В данной линии установлен теплогенератор вихревого типа, работающий на щепе. Опилки автоматически подаются в сушку через просеивающее устройство барабанного типа для отделения крупных частиц и коры. В сите в зимнее время осуществляется камнедробление смерзшихся комков. После сушки сырье додрабливается, поступает в гранулятор, охладитель, сито и на фасовку.',
        image: '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2018-06-granulation-kirov-video.mp4',
        gallery: [
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-main.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-1.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-2.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-3.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-4.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-5.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-6.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-7.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-8.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-9.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-10.webp',
        ],
        slug: '2018-06-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Теплогенератор вихревого типа на щепе',
        ]
    },
    {
        id: 15,
        title: 'Линия сушки',
        location: 'Кировская область',
        year: '2018',
        month: 'Май',
        category: 'Сушка',
        description: 'Сушильный комплекс на базе теплогенератора для подготовки опила к дальнейшему брикетированию или гранулированию.',
        image: '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2018-05-drying-kirov-video.mp4',
        gallery: [
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-main.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-1.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-2.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-3.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-4.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-5.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-6.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-7.webp',
        ],
        slug: '2018-05-drying-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 16,
        title: 'Линия гранулирования',
        location: 'Кировская область',
        year: '2017',
        month: 'Декабрь',
        category: 'Гранулирование',
        description: 'Стружка засасывается с помощью вакуумной молотковой дробилки, измельчается и подается в бункер-накопитель, далее поступает в гранулятор. Полученные гранулы охлаждаются в охладителе, просеиваются и поступают на фасовку.',
        image: '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-main.webp',
        gallery: [
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-main.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-1.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-2.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-3.webp',
        ],
        slug: '2017-12-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухая стружка хвойных пород',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 17,
        title: 'Линия гранулирования',
        location: 'Республика Коми',
        year: '2017',
        month: 'Ноябрь',
        category: 'Гранулирование',
        description: 'Сырьем является опил и горбыль. Горбыль подается в рубительную машину, далее щепа поступает в молотковую дробилку и по скребковому транспортеру — в сушку, опилки сразу подаются на скребковый транспортер. После сушки сырье додрабливается, поступает в бункер-накопитель, гранулятор, охладитель, сито и на фасовку.',
        image: '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-main.webp',
        gallery: [
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-main.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-1.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-2.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-3.webp',
        ],
        slug: '2017-11-granulation-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, горбыль хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Рубительная машина для горбыля',
        ]
    },
    {
        id: 18,
        title: 'Линия брикетирования Pini & kay',
        location: 'Саратовская область',
        year: '2016',
        month: 'Ноябрь',
        category: 'Брикетирование',
        description: 'Линия брикетирования Pini & kay из сухого опила хвойных пород.',
        image: '/images/projects/2016/2016-11-briquetting-saratov/2016-11-briquetting-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-11-briquetting-saratov/2016-11-briquetting-saratov-main.webp',
        ],
        slug: '2016-11-briquetting-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухой опил хвойных пород',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 19,
        title: 'Линия гранулирования',
        location: 'Саратовская область',
        year: '2016',
        month: 'Август',
        category: 'Гранулирование',
        description: 'Сырье засасывается с помощью вакуумной молотковой дробилки, измельчается и подается в бункер-накопитель, далее поступает в гранулятор. Полученные гранулы охлаждаются в охладителе, просеиваются и поступают на фасовку.',
        image: '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-main.webp',
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-gallery-1.webp',
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-gallery-2.webp',
        ],
        slug: '2016-08-granulation-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Шелуха подсолнуха, влажность до 14%',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 20,
        title: 'Линия брикетирования Pini & kay',
        location: 'Пензенская область',
        year: '2016',
        month: 'Август',
        category: 'Брикетирование',
        description: 'Линия брикетирования Pini & kay из опила естественной влажности.',
        image: '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-main.webp',
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-gallery-1.webp',
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-gallery-2.webp',
        ],
        slug: '2016-08-briquetting-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, естественная влажность',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 21,
        title: 'Линия брикетирования Pini & kay',
        location: 'Пермский край',
        year: '2016',
        month: 'Январь',
        category: 'Брикетирование',
        description: 'Нами был установлен участок брикетирования. Оборудование по подготовке сырья (дробление и сушка) были установлены заказчиком предварительно.',
        image: '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2016-01-briquetting-perm-video.mp4',
        gallery: [
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-main.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-1.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-2.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-3.webp',
        ],
        slug: '2016-01-briquetting-perm',
        capacity: '600 кг/час',
        specs: [
            'Сырье: Щепа, опил хвойных пород, естественная влажность',
            'Производительность: 600 кг/час',
        ]
    },
    {
        id: 22,
        title: 'Линия брикетирования Pini & kay',
        location: 'Республика Северная Осетия',
        year: '2015',
        month: 'Сентябрь',
        category: 'Брикетирование',
        description: 'Нами был установлен участок брикетирования. Оборудование по подготовке сырья (дробление и сушка) были установлены заказчиком предварительно.',
        image: '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2015-09-briquetting-ossetia-video.mp4',
        gallery: [
            '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-main.webp',
            '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-gallery-1.webp',
        ],
        slug: '2015-09-briquetting-ossetia',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Тонкомер, горбыль лиственных пород',
            'Производительность: 1000 кг/час',
        ]
    },
    {
        id: 23,
        title: 'Линия гранулирования',
        location: 'Омутнинск (Кировская обл.)',
        year: '2014',
        month: 'Январь',
        category: 'Гранулирование',
        description: 'Стружка засасывается с помощью вакуумной молотковой дробилки, измельчается и подается в бункер-накопитель, далее поступает в гранулятор. Полученные гранулы охлаждаются в охладителе, просеиваются и поступают на фасовку.',
        image: '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-main.webp',
        video: 'https://cdn.kirovbelmash-site.ru/2014-01-granulation-kirov-video.mp4',
        gallery: [
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-main.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-1.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-2.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-3.webp',
        ],
        slug: '2014-01-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухая стружка хвойных пород',
            'Производительность: 1000 кг/час',
        ]
    }
];

export interface Project {
    id: number;
    title: string;
    category: string;
    location: string;
    year: string;
    month: string;
    description: string;
    image: string;
    video?: string;
    gallery?: string[];
    slug: string;
    capacity?: string;
    equipment?: string[];
    specs?: string[];
    client?: string;
    duration?: string;
}

export const projectCategories = ['Все', 'Брикетирование', 'Гранулирование', 'Сушка', 'Комбинированные линии'];

export const testimonials = [
    {
        id: 1,
        name: 'Алексей Петров',
        position: 'Генеральный директор',
        company: 'ООО «ЛесПром»',
        location: 'Кировская область',
        rating: 5,
        text: 'Заказали линию брикетирования RUF 4 — от проектирования до запуска прошло всего 3 месяца. Оборудование работает стабильно уже год, производительность полностью соответствует заявленной. Отдельное спасибо за оперативную техподдержку.',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20middle%20aged%20Russian%20businessman%20in%20suit%20confident%20expression%20neutral%20background%20corporate%20headshot%20photography&width=80&height=80&seq=av1&orientation=squarish',
        projectId: 1,
    },
    {
        id: 2,
        name: 'Ирина Козлова',
        position: 'Директор по производству',
        company: 'АО «БиоТопливо»',
        location: 'Московская область',
        rating: 5,
        text: 'Сотрудничаем с КировБелМаш уже третий год. Установили комплекс Cypress Nemesis — качество брикетов превосходное, клиенты довольны. Система рекуперации тепла реально экономит на энергозатратах. Рекомендуем!',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20Russian%20businesswoman%20in%20her%2040s%20wearing%20blazer%20confident%20smile%20neutral%20background%20corporate%20headshot%20photography&width=80&height=80&seq=av2&orientation=squarish',
        projectId: 2,
    },
    {
        id: 3,
        name: 'Дмитрий Волков',
        position: 'Владелец',
        company: 'ИП Волков Д.С.',
        location: 'Вологодская область',
        rating: 5,
        text: 'Брали сушильный комплекс АС-3. Ребята помогли с подбором оборудования, приехали на монтаж, обучили персонал. Сушилка работает на наших же отходах — экономия на топливе колоссальная. Окупилось за 8 месяцев.',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20young%20Russian%20man%20entrepreneur%20in%20casual%20business%20attire%20friendly%20expression%20neutral%20background%20headshot%20photography&width=80&height=80&seq=av3&orientation=squarish',
        projectId: 4,
    },
    {
        id: 4,
        name: 'Сергей Михайлов',
        position: 'Технический директор',
        company: 'ООО «СеверЛес»',
        location: 'Республика Коми',
        rating: 4,
        text: 'Установили линию Nestro для переработки отходов нашей лесопилки. Качество брикетов отличное, автоматическая упаковка сильно упрощает логистику. Единственное — доставка заняла чуть дольше, чем планировали, но результат того стоит.',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20Russian%20man%20in%20his%2050s%20wearing%20glasses%20and%20business%20shirt%20serious%20expression%20neutral%20background%20corporate%20headshot%20photography&width=80&height=80&seq=av4&orientation=squarish',
        projectId: 5,
    },
    {
        id: 5,
        name: 'Андрей Новиков',
        position: 'Руководитель проекта',
        company: 'ГК «ТимберГрупп»',
        location: 'Красноярский край',
        rating: 5,
        text: 'Заказали комплексную линию переработки на 40 тонн в сутки. Масштабный проект, но команда КировБелМаш справилась на отлично. Автоматизация на высшем уровне — линия работает практически без участия оператора.',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20Russian%20man%20in%20his%2030s%20wearing%20polo%20shirt%20confident%20look%20neutral%20background%20corporate%20headshot%20photography&width=80&height=80&seq=av5&orientation=squarish',
        projectId: 8,
    },
    {
        id: 6,
        name: 'Елена Соколова',
        position: 'Финансовый директор',
        company: 'ООО «ПеллетМастер»',
        location: 'Пермский край',
        rating: 5,
        text: 'Выбрали компактную линию ГТ-500 для нашего небольшого производства. Идеальное соотношение цены и качества. Монтаж за 5 дней — и мы уже производим пеллеты. Инвестиция окупилась быстрее, чем рассчитывали.',
        avatar:
            'https://readdy.ai/api/search-image?query=professional%20portrait%20of%20Russian%20businesswoman%20in%20her%2030s%20with%20blonde%20hair%20wearing%20elegant%20blouse%20warm%20smile%20neutral%20background%20headshot%20photography&width=80&height=80&seq=av6&orientation=squarish',
        projectId: 7,
    },
];

export const projectStats = [
    { value: '80+', label: 'Реализованных проектов' },
    { value: '35+', label: 'Регионов России' },
    { value: '98%', label: 'Довольных клиентов' },
    { value: '10', label: 'Лет на рынке' },
];
