export const projectsData: Project[] = [
    {
        id: 1,
        title: 'Линия брикетирования Pini & kay',
        location: 'Никольск (Вологодская обл.)',
        year: '2025',
        month: 'Август',
        category: 'Брикетирование',
        description: 'Сырье подается в накопительный бункер, далее проходя через аэродинамическую сушильную линию поступает на брикетирование. Готовый продукт — брикет Pini & kay.',
        image: '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-video.mp4',
        gallery: [
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-main.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-1.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-2.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-3.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-4.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-5.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-6.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-7.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-8.webp',
            '/images/projects/2025/2025-08-briquetting-vologda/2025-08-briquetting-vologda-gallery-9.webp',
        ],
        slug: '2025-08-briquetting-vologda',
        capacity: '500 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 500 кг/час',
            'Аэродинамическая сушильная линия',
        ],
        composition: [
            'Бункер приемный 5 м. куб. (ворошитель бункера)',
            'Сепаратор дисковый (система камнедробления)',
            'Транспортер шнековый L-4м',
            'Сушка опилок аэродинамическая 2х контурная',
            'Дробильная установка ДСС (комплект воздуховодов)',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 3 м. куб. (дозирующее устройство)',
            'Пресс экструдер ПБМ-2',
            'Автомат резки брикета (зонд вытяжной)',
            'Система дымоудаления',
            'Электрощит управления участком прессования',
        ],
    },
    {
        id: 2,
        title: 'Линия брикетирования (пресс Nielsen)',
        location: 'Борисово-Судское (Вологодская обл.)',
        year: '2025',
        month: 'Июль',
        category: 'Брикетирование',
        description: 'В данной линии установлены три приёмных живых пола: первый — для крупного сырья, второй — для мелкого сырья, третий — для топлива теплогенератора. Мелкое сырье сразу поступает в сушку, крупное проходит через дробилку. После сушки сырьё поступает в ударно-набивной пресс. Дополнительно установлен стокерный склад для накопления высушенного сырья перед прессованием.',
        image: '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-main.webp',
        gallery: [
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-main.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-1.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-2.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-3.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-4.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-5.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-6.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-7.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-8.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-9.webp',
            '/images/projects/2025/2025-07-drying-vologda/2025-07-drying-vologda-gallery-10.webp',
        ],
        slug: '2025-07-drying-vologda',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Три приёмных живых пола',
            'Стокерный склад для накопления сырья',
            'Ударно-набивной пресс Nielsen',
        ],
        composition: [
            'Автоматическая подача сырья Живое дно гидравлическое 35м.куб',
            'Сепаратор дисковый',
            'Система камнедробления',
            'Транспортер цепной L-образный',
            'Автоматическая подача сырья Живое дно гидравлическое 35м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Бункер промежуточный 400л',
            'Дозатор шнековый (подача сырья в сушку)',
            'Транспортер цепной прямой',
            'Бункер-накопитель щепы 1м.куб',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Теплогенератор ТГН 1,5 МВт',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0.65',
            'Затвор шлюзовой ШУ-4',
            'Транспортер цепной прямой',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 6 м.куб',
            'Автоматическая подача сырья Живое дно гидравлическое 25м.куб',
            'Транспортер цепной прямой',
            'Задвижка шиберная',
            'Транспортер цепной L-образный',
            'Автоматическая подача сырья Живое дно гидравлическое 35м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Транспортер цепной прямой',
        ],
    },
    {
        id: 3,
        title: 'Линия брикетирования',
        location: 'Пермский край',
        year: '2025',
        month: 'Июнь',
        category: 'Брикетирование',
        description: 'Сырьё в данной линии — опил и щепа. Всё сырьё просеивается и делится на фракции: мелкое сырьё сразу уходит в сушку, крупное проходит через дробилку и поступает в сушку. После сушки сырьё брикетируется.',
        image: '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-video.mp4',
        gallery: [
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-main.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-1.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-2.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-3.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-4.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-5.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-6.webp',
            '/images/projects/2025/2025-06-briquetting-perm/2025-06-briquetting-perm-gallery-7.webp',
        ],
        slug: '2025-06-briquetting-perm',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Просев и разделение сырья на фракции',
        ],
        composition: [
            'Автоматич. подача сырья Живое дно гидравлическое 35м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Устройство просеивающее',
            'Задвижка шиберная',
            'Транспортер цепной прямой',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Бункер промежуточный 400л',
            'Дозатор шнековый (подача сырья в сушку)',
            'Теплогенератор ТГН 1,5 МВт',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой ШУ-4',
            'Транспортер цепной прямой, 400 мм',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 6м.куб',
            'Пресс экструдер ПБМ-2',
            'Электрощит управления участком прессования',
        ],
    },
    {
        id: 4,
        title: 'Линия брикетирования (пресс Nielsen)',
        location: 'Усть-Кулом (Республика Коми)',
        year: '2024',
        month: 'Апрель',
        category: 'Брикетирование',
        description: 'В данной линии установлены два приёмных живых пола: в один насыпается крупное сырьё, в другой — мелкое. Мелкое сырьё сразу поступает в сушку, крупное проходит через дробилку. После сушки сырьё поступает в ударно-набивной пресс.',
        image: '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-main.webp',
        gallery: [
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-main.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-1.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-2.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-3.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-4.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-5.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-6.webp',
            '/images/projects/2024/2024-04-drying-komi/2024-04-drying-komi-gallery-7.webp',
        ],
        slug: '2024-04-drying-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Два приёмных живых пола',
            'Ударно-набивной пресс Nielsen',
        ],
        composition: [
            'Автоматическая подача сырья живое дно 50м.куб (гидравлическое)',
            'Сепаратор дисковый',
            'Автоматическая подача сырья живое дно 30м.куб (гидравлическое)',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Транспортер цепной L-образный',
            'Транспортер ленточный',
            'Бункер накопитель промежуточный 1 м.куб',
            'Дозатор шнековый (подача сырья в сушку)',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Теплогенератор ТГН-1,5',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой ШУ-4',
            'Дробильная установка КДС',
            'Бункер накопитель 6 м.куб',
            'Электрощит управления сушильной линией',
        ],
    },
    {
        id: 5,
        title: 'Линия гранулирования',
        location: 'Никольск (Вологодская обл.)',
        year: '2023',
        month: 'Декабрь',
        category: 'Гранулирование',
        description: 'Сырьё в данной линии — опил и щепа естественной влажности. Всё сырьё просеивается и делится на фракции: мелкое сырьё сразу уходит в сушку, крупное проходит через дробилку.',
        image: '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-main.webp',
        gallery: [
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-main.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-1.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-2.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-3.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-4.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-5.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-6.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-7.webp',
            '/images/projects/2023/2023-12-granulation-vologda/2023-12-granulation-vologda-gallery-8.webp',
        ],
        slug: '2023-12-granulation-vologda',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, щепа естественной влажности',
            'Производительность: 1000 кг/час',
            'Просев и разделение сырья на фракции',
        ],
        composition: [
            'Автоматическая подача сырья Живое гидравлическое',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Устройство просеивающее',
            'Транспортер цепной прямой',
            'Дозатор шнековый (подача сырья в сушку)',
            'Бункер-накопитель промежуточный 400л',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Теплогенератор ТГН 1,5МВт',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой ШУ-4',
            'Дробильная установка ДСС (ременная передача)',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 6м.куб',
            'Гранулятор ОГМ-1.5',
            'Элеватор ЛГ-120',
            'Колонна охлаждения',
            'Фильтровальная установка',
            'Транспортер ленточный гофроборт',
            'Весы электронные',
            'Электрощит управления участком прессования',
            'Транспортер ленточный',
        ],
    },
    {
        id: 6,
        title: 'Линия брикетирования Pini & kay',
        location: 'Мирный (Кировская обл.)',
        year: '2023',
        month: 'Июнь',
        category: 'Брикетирование',
        description: 'Горбыль измельчается в щепу в рубительной машине. Получаемая щепа поступает в накопитель «Живое дно», откуда подаётся в теплогенератор (в качестве топлива) и в дробильную установку для предварительного измельчения. Из дробилки сырьё поступает в сушильный барабан, затем додрабливается в вакуумной дробилке и через шнековый дозатор — в брикетирующий пресс.',
        image: '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-main.webp',
        gallery: [
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-main.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-1.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-2.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-3.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-4.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-5.webp',
            '/images/projects/2023/2023-06-briquetting-kirov/2023-06-briquetting-kirov-gallery-6.webp',
        ],
        slug: '2023-06-briquetting-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Горбыль, щепа хвойных пород',
            'Производительность: 1000 кг/час',
            'Рубительная машина для горбыля',
            'Вакуумная молотковая дробилка',
        ],
        composition: [
            'Автоматическая подача сырья Живое дно гидравлическое 40м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Рубительная машина РДМ-30',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Теплогенератор ТГН-1,5мВт',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой ШУ-4',
            'Дробильная установка ДСС',
            'Фильтровальная установка',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 6м.куб',
            'Пресс экструдер ПБМ-2',
            'Автомат резки брикета',
            'Система дымоудаления',
            'Электрощит управления участком прессования',
        ],
    },
    {
        id: 7,
        title: 'Линия брикетирования Pini & kay',
        location: 'Кез (Республика Удмуртия)',
        year: '2022',
        month: 'Декабрь',
        category: 'Брикетирование',
        description: 'Линия брикетирования (pini & kay) из сырых древесных опилок мелкой фракции. Сырье просеивается и сразу отправляется в сушку и далее на прессование.',
        image: '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-main.webp',
        gallery: [
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-main.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-1.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-2.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-3.webp',
            '/images/projects/2022/2022-12-briquetting-udmurtia/2022-12-briquetting-udmurtia-gallery-4.webp',
        ],
        slug: '2022-12-briquetting-udmurtia',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Бункер-приемный 5м.куб',
            'Сепаратор дисковый',
            'Транспортер шнековый L-3м',
            'Сушка опилок аэродинамическая',
            'Дробильная установка ДСС',
            'Электрощит управления сушильной линией',
            'Бункер-накопитель 3м.куб',
            'Пресс-экструдер ПБМ-2',
            'Автомат резки брикета',
            'Система дымоудаления',
            'Электрощит управления участком прессования',
        ],
    },
    {
        id: 8,
        title: 'Линия пеллетирования, брикетирования и сушки',
        location: 'Ханты-Мансийский АО — Югра',
        year: '2022',
        month: 'Декабрь',
        category: 'Комбинированные линии',
        description: 'Горбыль измельчается в щепу в рубительной машине. Далее щепа загружается в накопитель "Живое дно". Из "Живого дна" щепа автоматически поступает в дробилку для предварительного измельчения. После сушки сырьё поступает в пресс-гранулятор или пресс-брикетер. Теплогенератор сушки работает на газу.',
        image: '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-video.mp4',
        gallery: [
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-main.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-1.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-2.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-3.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-4.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-5.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-6.webp',
            '/images/projects/2022/2022-12-combined-khmao/2022-12-combined-khmao-gallery-8.webp',
        ],
        slug: '2022-12-combined-khmao',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Горбыль, щепа',
            'Производительность: 1000 кг/час',
            'Теплогенератор: газовый',
        ],
        composition: [
            'Автоматическая подача сырья Живое дно гидравлическое 40м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Рубительная машина РДМ-30',
            'Дозатор шнековый (подача сырья в дробильную установку)',
            'Дробильная установка КДЕ',
            'Теплогенератор 1 мВт (Газовый)',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой АВМ-0.65',
            'Дробильная установка ДСС',
            'Электрощит управления сушильной линией',
            'Бункер накопитель 6м.куб',
            'Гранулятор ОГМ-1.5',
            'Элеватор ЛГ-120',
            'Колонна охлаждения',
            'Транспортер ленточный гофроборт',
            'Весы электронные',
            'Электрощит управления участком гранулирования',
            'Пресс экструдер ПБМ-2',
            'Автомат резки брикета',
            'Система дымоудаления',
            'Электрощит управления участком брикетирования',
            'Бункер промежуточный 400л',
        ],
    },
    {
        id: 9,
        title: 'Линия сушки',
        location: 'Республика Коми',
        year: '2022',
        month: 'Август',
        category: 'Сушка',
        description: 'В данной линии осуществляется раздельная подача сырья на сушку и топлива для теплогенератора. Сырье в сушку поступает из живого дна №1. Топливо в теплогенератор поступает из живого дна №2. Таким образом сырье не смешивается и в качестве топлива можно использовать кору, некачественный опил и т.д.',
        image: '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2022/2022-08-drying-komi/2022-08-drying-komi-video.mp4',
        gallery: [
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-main.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-1.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-2.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-3.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-4.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-5.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-6.webp',
            '/images/projects/2022/2022-08-drying-komi/2022-08-drying-komi-gallery-7.webp',
        ],
        slug: '2022-08-drying-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил естественной влажности',
            'Производительность: 1000 кг/час',
            'Раздельная подача сырья и топлива',
        ],
        composition: [
            'Автоматическая подача сырья Живое дно гидравлическое 40м.куб',
            'Автоматическая подача сырья Живое дно гидравлическое 20м.куб',
            'Сепаратор дисковый',
            'Транспортер цепной L-образный',
            'Бункер промежуточный 400л',
            'Дозатор шнековый (подача сырья в сушку)',
            'Теплогенератор ТГН 1,5мВт',
            'Барабан сушильный АВМ-0,65',
            'Циклон АВМ-0,65',
            'Затвор шлюзовой ШУ-4',
            'Электрощит управления сушильной линией',
        ],
    },
    {
        id: 10,
        title: 'Линия брикетирования Pini & kay',
        location: 'Суслонгер (Республика Марий Эл)',
        year: '2020',
        month: 'Сентябрь',
        category: 'Брикетирование',
        description: 'Щепа с помощью гидравлического живого дна, проходя через сепаратор для отделения крупнокусковых включений, ссыпается на L-образный скребковый транспортер, из которого основная масса поступает в дробилку, а часть щепы подается в бункер теплогенератора в качестве топлива. Из дробилки измельченное сырье поступает в сушку, далее — на прессование.',
        image: '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-video.mp4',
        gallery: [
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-main.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-1.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-2.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-3.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-4.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-5.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-6.webp',
            '/images/projects/2020/2020-09-briquetting-mari-el/2020-09-briquetting-mari-el-gallery-7.webp',
        ],
        slug: '2020-09-briquetting-mari-el',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Щепа лиственных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Гидравлическое живое дно',
        ],
        composition: [
            'Транспортер ленточный',
            'Сепаратор дисковый',
            'Дробильная установка КДЕ',
            'Теплогенератор Вихревой',
            'Барабан сушильный АВМ-0.65',
            'Циклон АВМ-0.65',
            'Затвор шлюзовой ШУ-4',
            'Вентилятор',
            'Электрощит управления «Сушка»',
            'Бункер накопитель 6м.куб',
            'Пресс брикетирующий ПБМ-2',
            'Автомат резки брикета',
            'Дымоудаление',
            'Электрощит управления «Прессование»',
            'Автоматическая подача «Живое дно гидравлическое»',
            'Бункер промежуточный 400л',
            'Дозатор шнековый для подачи сырья в смеситель',
        ],
    },
    {
        id: 11,
        title: 'Линия гранулирования',
        location: 'Сыктывкар (Республика Коми)',
        year: '2020',
        month: 'Март',
        category: 'Гранулирование',
        description: 'Сырье из живого дна, проходя через сепаратор для отделения крупнокусковых включений, разделяется просеивающим устройством на мелкую (опил → в сушку) и крупную (щепа → в теплогенератор) фракции. При переполнении бункера теплогенератора крупная фракция перенаправляется в дробилку и далее в сушку.',
        image: '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-video.mp4',
        gallery: [
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-main.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-1.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-2.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-3.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-4.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-5.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-6.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-7.webp',
            '/images/projects/2020/2020-03-granulation-komi/2020-03-granulation-komi-gallery-8.webp',
        ],
        slug: '2020-03-granulation-komi',
        capacity: '2000 кг/час',
        specs: [
            'Сырье: Опил, щепа хвойных пород, естественная влажность',
            'Производительность: 2000 кг/час',
            'Раздельная подготовка фракций',
        ],
        composition: [
            'Транспортер скребковый цепной L-образный',
            'Транспортер шнековый с шибером',
            'Рубительная машина РМД-940',
            'Устройство просеивающее',
            'Дробильная установка КДЕ',
            'Теплогенератор ТГ-2000 вихревой 2.0 МВт',
            'Барабан сушильный АВМ-1,5',
            'Циклон АВМ-1,5',
            'Вентилятор АВМ-1,5',
            'Затвор шлюзовой ШУ-6',
            'Дробильная установка ДСС',
            'Электрощит управления «Сушка»',
            'Бункер накопитель 6м.куб с двумя дозирующее устройствами',
            'Гранулятор ОГМ-1.5',
            'Транспортер ленточный (гофроборт)',
            'Элеватор ЛГ-120',
            'Охладитель',
            'Транспортер ленточный (гофроборт)',
            'Электронные весы',
            'Электрощит управления «Прессование»',
            'Автоматическая подача «Живое дно гидравлическое»',
        ],
    },
    {
        id: 12,
        title: 'Линия сушки',
        location: 'Котлас (Архангельская обл.)',
        year: '2019',
        month: 'Сентябрь',
        category: 'Сушка',
        description: 'В данной линии осуществляется раздельная подача сырья на сушку и топлива для теплогенератора. Сырье в сушку поступает из живого дна №1 с помощью скребкового транспортера. Топливо в теплогенератор поступает из живого дна №2. Таким образом сырье не смешивается и в качестве топлива можно использовать кору, гнилой опил и т.д.',
        image: '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-main.webp',
        gallery: [
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-main.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-1.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-2.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-3.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-4.webp',
            '/images/projects/2019/2019-09-drying-kotlas/2019-09-drying-kotlas-gallery-5.webp',
        ],
        slug: '2019-09-drying-kotlas',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Раздельная подача сырья и топлива',
        ],
        composition: [
            'Барабан сушильный АВМ-0,65 с щитом управления',
            'Автоматическая подача сырья Подвижный пол',
        ],
    },
    {
        id: 13,
        title: 'Линия брикетирования RUF',
        location: 'Кировская область',
        year: '2019',
        month: 'Июль',
        category: 'Брикетирование',
        description: 'Сырьем для изготовления брикетов является опил, щепа и обрезь торцовки, которые ранее вывозились на спецплощадку. КировБелМаш спроектировал линию со шредером для измельчения обрезков в щепу, молотковой дробилкой и сушильным барабаном. После сушки из сырья прессуется брикет RUF.',
        image: '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-video.mp4',
        gallery: [
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-main.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-1.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-2.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-3.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-4.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-5.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-6.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-7.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-8.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-9.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-10.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-11.webp',
            '/images/projects/2019/2019-07-briquetting-kirov/2019-07-briquetting-kirov-gallery-12.webp',
        ],
        slug: '2019-07-briquetting-kirov',
        capacity: '600 кг/час',
        specs: [
            'Сырье: Опил, щепа, обрезь торцовки хвойных пород, естественная влажность',
            'Производительность: 600 кг/час',
            'Шредер для измельчения обрезков',
        ],
        composition: [
            'Транспортер скребковый цепной',
            'Транспортер ленточный',
            'Транспортер скребковый цепной',
            'Транспортер цепной скребковый',
            'Барабан сушильный АВМ-0,65 с щитом управления',
            'Транспортер скребковый цепной',
            'Циклон АВМ с вентилятором',
            'Шредер ШРП-800',
            'Шлюзовой затвор',
            'Дробильная установка КДЕ',
            'Подача сырья спаренное «Живое дно»',
        ],
    },
    {
        id: 14,
        title: 'Линия гранулирования',
        location: 'Кировская область',
        year: '2018',
        month: 'Июнь',
        category: 'Гранулирование',
        description: 'В данной линии установлен теплогенератор вихревого типа, работающий на щепе. Опилки автоматически подаются в сушку через просеивающее устройство барабанного типа для отделения крупных частиц и коры. В сите в зимнее время осуществляется камнедробление смерзшихся комков. После сушки сырье додрабливается, поступает в гранулятор, охладитель, сито и на фасовку.',
        image: '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-video.mp4',
        gallery: [
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-main.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-1.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-2.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-3.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-4.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-5.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-6.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-7.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-8.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-9.webp',
            '/images/projects/2018/2018-06-granulation-kirov/2018-06-granulation-kirov-gallery-10.webp',
        ],
        slug: '2018-06-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Теплогенератор вихревого типа на щепе',
        ],
        composition: [
            'Гранулятор ОГМ-1,5 с щитом управления',
            'Бункер накопитель 6м3с дозирующим устройством, выносной системой фильтрации',
            'Транспортер скребковый цепной',
            'Барабан сушильный (восстановленный) с щитом управления',
            'Циклон АВМ с вентилятором',
            'Шлюзовой затвор',
            'Теплогенератор вихревой с транспортером подачи топлива',
            'Охладитель',
            'Транспортер ленточный гофроборт',
            'Транспортер ленточный гофроборт',
            'Просеивающее устройство СБ',
            'Автоматическая подача сырья «Подвижный пол АВМ»',
        ],
    },
    {
        id: 15,
        title: 'Линия сушки',
        location: 'Кировская область',
        year: '2018',
        month: 'Май',
        category: 'Сушка',
        description: 'Сушильный комплекс на базе теплогенератора для подготовки опила к дальнейшему брикетированию или гранулированию.',
        image: '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-video.mp4',
        gallery: [
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-main.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-1.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-2.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-3.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-4.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-5.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-6.webp',
            '/images/projects/2018/2018-05-drying-kirov/2018-05-drying-kirov-gallery-7.webp',
        ],
        slug: '2018-05-drying-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Барабан сушильный АВМ-0,65 с щитом управления',
            'Циклон АВМ с вентилятором',
            'Шлюзовой затвор',
            'Теплогенератор вихревой с транспортером загрузки топлива',
            'Бункер накопитель 2,4 м.куб с дозирующим устройством',
            'Транспортер скребковый цепной',
            'Транспортер скребковый цепной',
        ],
    },
    {
        id: 16,
        title: 'Линия гранулирования',
        location: 'Кировская область',
        year: '2017',
        month: 'Декабрь',
        category: 'Гранулирование',
        description: 'Линия гранулирования из сухой стружки хвойных пород, 1000 кг/ч, Кировская область. Стружка засасывается вакуумной молотковой дробилкой, поступает в бункер-накопитель, гранулятор, охладитель и на фасовку.',
        image: '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-main.webp',
        gallery: [
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-main.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-1.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-2.webp',
            '/images/projects/2017/2017-12-granulation-kirov/2017-12-granulation-kirov-gallery-3.webp',
        ],
        slug: '2017-12-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухая стружка хвойных пород',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Пресс-гранулятор ОГМ-1,5 с щитом управления',
            'Бункер накопитель 3м3с дозирующим устройством',
            'Охладитель',
            'Транспортер ленточный гофроборт',
            'Дробильная установка ДСС',
            'Транспортер ленточный гофроборт',
        ],
    },
    {
        id: 17,
        title: 'Линия гранулирования',
        location: 'Республика Коми',
        year: '2017',
        month: 'Ноябрь',
        category: 'Гранулирование',
        description: 'Сырьем является опил и горбыль. Горбыль подается в рубительную машину, далее щепа поступает в молотковую дробилку и по скребковому транспортеру — в сушку, опилки сразу подаются на скребковый транспортер. После сушки сырье додрабливается, поступает в бункер-накопитель, гранулятор, охладитель, сито и на фасовку.',
        image: '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-main.webp',
        gallery: [
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-main.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-1.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-2.webp',
            '/images/projects/2017/2017-11-granulation-komi/2017-11-granulation-komi-gallery-3.webp',
        ],
        slug: '2017-11-granulation-komi',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, горбыль хвойных пород, естественная влажность',
            'Производительность: 1000 кг/час',
            'Рубительная машина для горбыля',
        ],
        composition: [
            'Циклон АВМ с вентилятором',
            'Шлюзовой затвор',
            'Барабан сушильный с щитом управления',
            'Охладитель',
            'Транспортер ленточный гофроборт',
            'Бункер накопитель 6м3с дозирующим устройством',
            'Транспортер скребковый цепной',
            'Теплогенератор (кирпичный)',
            'Пресс гранулятор с щитом управления',
        ],
    },
    {
        id: 18,
        title: 'Линия брикетирования Pini & kay',
        location: 'Саратовская область',
        year: '2016',
        month: 'Ноябрь',
        category: 'Брикетирование',
        description: 'Линия брикетирования Pini & kay производительностью 1000 кг/ч из сухого опила хвойных пород в Саратовской области. Сырьё поступало сразу на прессование без дополнительной подготовки.',
        image: '/images/projects/2016/2016-11-briquetting-saratov/2016-11-briquetting-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-11-briquetting-saratov/2016-11-briquetting-saratov-main.webp',
        ],
        slug: '2016-11-briquetting-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухой опил хвойных пород',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Прес брикетирующий ПБМ-2 с щитом управления',
            'Станок для автоматической торцовки брикета',
            'Бункер-накопитель с двумя дозирующими устройствами',
        ],
    },
    {
        id: 19,
        title: 'Линия гранулирования',
        location: 'Саратовская область',
        year: '2016',
        month: 'Август',
        category: 'Гранулирование',
        description: 'Линия гранулирования из шелухи подсолнуха, 1000 кг/ч, Саратовская область. Сырье засасывается вакуумной молотковой дробилкой, поступает в бункер-накопитель, гранулятор, охладитель и на фасовку.',
        image: '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-main.webp',
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-gallery-1.webp',
            '/images/projects/2016/2016-08-granulation-saratov/2016-08-granulation-saratov-gallery-2.webp',
        ],
        slug: '2016-08-granulation-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Шелуха подсолнуха, влажность до 14%',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Пресс-гранулятор ОГМ-1,5 с щитом управления',
            'Бункер накопитель 3м3с дозирующим устройством',
            'Система фильтрации',
            'Охладитель',
            'Транспортер ленточный гофроборт',
            'Дробильная установка ДСС',
            'Транспортер ленточный гофроборт',
        ],
    },
    {
        id: 20,
        title: 'Линия брикетирования Pini & kay',
        location: 'Пензенская область',
        year: '2016',
        month: 'Август',
        category: 'Брикетирование',
        description: 'Линия брикетирования Pini & kay производительностью 1000 кг/ч из опила естественной влажности в Пензенской области. В составе линии — сушка, дробление и прессование.',
        image: '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-main.webp',
        gallery: [
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-main.webp',
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-gallery-1.webp',
            '/images/projects/2016/2016-08-briquetting-saratov/2016-08-briquetting-saratov-gallery-2.webp',
        ],
        slug: '2016-08-briquetting-saratov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Опил, естественная влажность',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Пресс-экструдер для производства топливных брикетов с щитом управления',
            'Бункер накопитель 6м.куб с дозирующим устройством',
            'Транспортер скребковый цепной',
            'Циклон',
            'Барабан сушильный АВМ-0,65 1000кг/час с щитом управления',
            'Теплогенератор кирпичный',
            'Дробильная установка КДС',
            'Просеивающее устройство СБ',
            'Станок для автоматической торцовки',
            'Транспортер цепной скребковый',
            'Транспортер ленточный',
            'Подача сырья «Подвижнй пол АВМ»',
            'Линия автоматической упаковки',
            'Система дымоудаления',
        ],
    },
    {
        id: 21,
        title: 'Линия брикетирования Pini & kay',
        location: 'Пермский край',
        year: '2016',
        month: 'Январь',
        category: 'Брикетирование',
        description: 'Монтаж участка брикетирования Pini & kay, 600 кг/ч, из щепы и опила хвойных пород в Пермском крае. Оборудование подготовки сырья (дробление и сушка) было установлено заказчиком заранее.',
        image: '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-video.mp4',
        gallery: [
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-main.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-1.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-2.webp',
            '/images/projects/2016/2016-01-briquetting-perm/2016-01-briquetting-perm-gallery-3.webp',
        ],
        slug: '2016-01-briquetting-perm',
        capacity: '600 кг/час',
        specs: [
            'Сырье: Щепа, опил хвойных пород, естественная влажность',
            'Производительность: 600 кг/час',
        ],
        composition: [
            'Пресс брикетирующий ПБМ-2 с щитом управления',
            'Бункер-накопитель с дозирующим устройством',
            'Станок для автоматической торцовки брикета',
            'Система дымоудаления',
        ],
    },
    {
        id: 22,
        title: 'Линия брикетирования Pini & kay',
        location: 'Республика Северная Осетия',
        year: '2015',
        month: 'Сентябрь',
        category: 'Брикетирование',
        description: 'Монтаж участка брикетирования Pini & kay, 1000 кг/ч, из тонкомера и горбыля лиственных пород в Республике Северная Осетия. Оборудование подготовки сырья установлено заказчиком предварительно.',
        image: '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-video.mp4',
        gallery: [
            '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-main.webp',
            '/images/projects/2015/2015-09-briquetting-ossetia/2015-09-briquetting-ossetia-gallery-1.webp',
        ],
        slug: '2015-09-briquetting-ossetia',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Тонкомер, горбыль лиственных пород',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Бункер-накопитель 6м.куб с двумя дозирующими устройствами',
            'Пресс-экструдер ПБМ-2',
            'Автомат резки брикета',
            'Система дымоудаления',
        ],
    },
    {
        id: 23,
        title: 'Линия гранулирования',
        location: 'Омутнинск (Кировская обл.)',
        year: '2014',
        month: 'Январь',
        category: 'Гранулирование',
        description: 'Линия гранулирования из сухой стружки хвойных пород, 1000 кг/ч, г. Омутнинск (Кировская обл.). Стружка обрабатывается вакуумной молотковой дробилкой, гранулируется, охлаждается и поступает на фасовку.',
        image: '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-main.webp',
        video: 'https://cdn.kirovbelmash.ru/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-video.mp4',
        gallery: [
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-main.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-1.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-2.webp',
            '/images/projects/2014/2014-01-granulation-kirov/2014-01-granulation-kirov-gallery-3.webp',
        ],
        slug: '2014-01-granulation-kirov',
        capacity: '1000 кг/час',
        specs: [
            'Сырье: Сухая стружка хвойных пород',
            'Производительность: 1000 кг/час',
        ],
        composition: [
            'Пресс-гранулятор ОГМ-1,5 с щитом управления',
            'Бункер накопитель 3м.куб с дозирующим устройством',
            'Система фильтрации',
            'Охладитель',
            'Транспортер ленточный гофроборт',
            'Дробильная установка ДСС',
            'Транспортер ленточный гофроборт',
        ],
    }
];

export interface Project {
    id: number;
    title: string;
    category: string;
    location: string;
    year: string;
    month: string;
    description: string;
    image: string;
    video?: string;
    gallery?: string[];
    slug: string;
    capacity?: string;
    equipment?: string[];
    specs?: string[];
    composition?: string[];
    client?: string;
    duration?: string;
}

export const projectCategories = ['Все', 'Брикетирование', 'Гранулирование', 'Сушка', 'Комбинированные линии'];

export const testimonials = [
    {
        id: 1,
        name: 'Алексей Петров',
        position: 'Генеральный директор',
        company: 'ООО «ЛесПром»',
        location: 'Кировская область',
        rating: 5,
        text: 'Заказали линию брикетирования RUF 4 — от проектирования до запуска прошло всего 3 месяца. Оборудование работает стабильно уже год, производительность полностью соответствует заявленной. Отдельное спасибо за оперативную техподдержку.',
        avatar: '/images/projects/testimonials/avatar-1.jpg',
        projectId: 1,
    },
    {
        id: 2,
        name: 'Ирина Козлова',
        position: 'Директор по производству',
        company: 'АО «БиоТопливо»',
        location: 'Московская область',
        rating: 5,
        text: 'Сотрудничаем с КировБелМаш уже третий год. Установили комплекс Cypress Nemesis — качество брикетов превосходное, клиенты довольны. Система рекуперации тепла реально экономит на энергозатратах. Рекомендуем!',
        avatar: '/images/projects/testimonials/avatar-2.jpg',
        projectId: 2,
    },
    {
        id: 3,
        name: 'Дмитрий Волков',
        position: 'Владелец',
        company: 'ИП Волков Д.С.',
        location: 'Вологодская область',
        rating: 5,
        text: 'Брали сушильный комплекс АС-3. Ребята помогли с подбором оборудования, приехали на монтаж, обучили персонал. Сушилка работает на наших же отходах — экономия на топливе колоссальная. Окупилось за 8 месяцев.',
        avatar: '/images/projects/testimonials/avatar-3.jpg',
        projectId: 4,
    },
    {
        id: 4,
        name: 'Сергей Михайлов',
        position: 'Технический директор',
        company: 'ООО «СеверЛес»',
        location: 'Республика Коми',
        rating: 4,
        text: 'Установили линию Nestro для переработки отходов нашей лесопилки. Качество брикетов отличное, автоматическая упаковка сильно упрощает логистику. Единственное — доставка заняла чуть дольше, чем планировали, но результат того стоит.',
        avatar: '/images/projects/testimonials/avatar-4.jpg',
        projectId: 5,
    },
    {
        id: 5,
        name: 'Андрей Новиков',
        position: 'Руководитель проекта',
        company: 'ГК «ТимберГрупп»',
        location: 'Красноярский край',
        rating: 5,
        text: 'Заказали комплексную линию переработки на 40 тонн в сутки. Масштабный проект, но команда КировБелМаш справилась на отлично. Автоматизация на высшем уровне — линия работает практически без участия оператора.',
        avatar: '/images/projects/testimonials/avatar-5.jpg',
        projectId: 8,
    },
    {
        id: 6,
        name: 'Елена Соколова',
        position: 'Финансовый директор',
        company: 'ООО «ПеллетМастер»',
        location: 'Пермский край',
        rating: 5,
        text: 'Выбрали компактную линию ГТ-500 для нашего небольшого производства. Идеальное соотношение цены и качества. Монтаж за 5 дней — и мы уже производим пеллеты. Инвестиция окупилась быстрее, чем рассчитывали.',
        avatar: '/images/projects/testimonials/avatar-6.jpg',
        projectId: 7,
    },
];

export const projectStats = [
    { value: '80+', label: 'Реализованных проектов' },
    { value: '35+', label: 'Регионов России' },
    { value: '98%', label: 'Довольных клиентов' },
    { value: '14', label: 'Лет на рынке' },
];
